#ifndef __MODULE_REC_MUXER_H__
#define __MODULE_REC_MUXER_H__

#include "gavin_error.h"
#include "../module_base.h"

//自定义错误ID，必须大于64，否则会与通用ID冲突
typedef enum _int_mod_rec_muxer_err_code_e{
	INT_MOD_REC_MUXER_ERR_INVALID_MUXTYPE = 64,			//非法录像类型
}int_mod_rec_muxer_err_code_e;

#define INTMODULE_REC_MUXER_OK 1
#define INTMODULE_REC_MUXER_FALSE 0
#define INTMODULE_REC_MUXER_ERR_INVALID_DEVID			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_INVALID_DEVID)//无效设备ID
#define INTMODULE_REC_MUXER_ERR_INVALID_CHNID			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_INVALID_CHNID)//无效通道ID
#define INTMODULE_REC_MUXER_ERR_ILLEGAL_PARAM			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_ILLEGAL_PARAM)//非法参数
#define INTMODULE_REC_MUXER_ERR_EXIST			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_EXIST)//源已经存在
#define INTMODULE_REC_MUXER_ERR_UNEXIST			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_UNEXIST)//源已不存在
#define INTMODULE_REC_MUXER_ERR_NULL_PTR			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NULL_PTR)//空指针
#define INTMODULE_REC_MUXER_ERR_NOT_CONFIG			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOT_CONFIG)//未初始化配置属性
#define INTMODULE_REC_MUXER_ERR_NOT_SUPPORT			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOT_SUPPORT)//操作或类型不支持
#define INTMODULE_REC_MUXER_ERR_NOT_PERM			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOT_PERM)//操作不允许
#define INTMODULE_REC_MUXER_ERR_NOT_NOMEM			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOMEM)//申请内存失败
#define INTMODULE_REC_MUXER_ERR_NOT_NOBUF			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOBUF)//申请buffer失败
#define INTMODULE_REC_MUXER_ERR_BUF_EMPTY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BUF_EMPTY)//buffer没有数据
#define INTMODULE_REC_MUXER_ERR_BUF_FULL			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BUF_FULL)//buffer满了
#define INTMODULE_REC_MUXER_ERR_SYS_NOTREADY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_SYS_NOTREADY)//系统未准备
#define INTMODULE_REC_MUXER_ERR_BADADDR			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BADADDR)//错误地址
#define INTMODULE_REC_MUXER_ERR_BUSY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BUSY)//资源被占用
#define INTMODULE_REC_MUXER_ERR_INVALID_MUXTYPE			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_REC_MUXER, GAVIN_ERR_LEVEL_ERROR, INT_MOD_REC_MUXER_ERR_INVALID_MUXTYPE)//非法录像类型

#ifdef __cplusplus
extern "C"{
#endif



#ifdef __cplusplus
};
#endif

#endif