/******************************
Dummy is a sample file of how to use module
*******************************/

#ifndef __MODULE_DUMMY_H__
#define __MODULE_DUMMY_H__

#include "gavin_error.h"
#include "../module_base.h"

typedef enum _int_mod_dummy_err_code_e{
	INT_MOD_DUMMY_ERR_MODULE_ID = 64,		//非法模块ID
	INT_MOD_DUMMY_ERR_PARSE_JSON,			//解析json异常
	INT_MOD_DUMMY_ERR_JSON_OBJ_EMPTY,		//json对象为空
	INT_MOD_DUMMY_ERR_SET_EMPTY,			//module集合为空
	INT_MOD_DUMMY_ERR_MATCH,				//module匹配失败
	INT_MOD_DUMMY_ERR_INITED,				//module已经初始化
}int_mod_dummy_err_code_e;

#define INTMODULE_DUMMY_OK 1
#define INTMODULE_DUMMY_FALSE 0
#define INTMODULE_DUMMY_ERR_INVALID_DEVID			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_INVALID_DEVID)//无效设备ID
#define INTMODULE_DUMMY_ERR_INVALID_CHNID			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_INVALID_CHNID)//无效通道ID
#define INTMODULE_DUMMY_ERR_ILLEGAL_PARAM			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_ILLEGAL_PARAM)//非法参数
#define INTMODULE_DUMMY_ERR_EXIST			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_EXIST)//源已经存在
#define INTMODULE_DUMMY_ERR_UNEXIST			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_UNEXIST)//源已不存在
#define INTMODULE_DUMMY_ERR_NULL_PTR			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NULL_PTR)//空指针
#define INTMODULE_DUMMY_ERR_NOT_CONFIG			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOT_CONFIG)//未初始化配置属性
#define INTMODULE_DUMMY_ERR_NOT_SUPPORT			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOT_SUPPORT)//操作或类型不支持
#define INTMODULE_DUMMY_ERR_NOT_PERM			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOT_PERM)//操作不允许
#define INTMODULE_DUMMY_ERR_NOT_NOMEM			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOMEM)//申请内存失败
#define INTMODULE_DUMMY_ERR_NOT_NOBUF			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_NOBUF)//申请buffer失败
#define INTMODULE_DUMMY_ERR_BUF_EMPTY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BUF_EMPTY)//buffer没有数据
#define INTMODULE_DUMMY_ERR_BUF_FULL			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BUF_FULL)//buffer满了
#define INTMODULE_DUMMY_ERR_SYS_NOTREADY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_SYS_NOTREADY)//系统未准备
#define INTMODULE_DUMMY_ERR_BADADDR			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BADADDR)//错误地址
#define INTMODULE_DUMMY_ERR_BUSY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, GAVIN_ERR_BUSY)//资源被占用
#define INTMODULE_DUMMY_ERR_MODULE_ID			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, INT_MOD_DUMMY_ERR_MODULE_ID)//非法模块ID
#define INTMODULE_DUMMY_ERR_PARSE_JSON			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, INT_MOD_DUMMY_ERR_PARSE_JSON)//解析json异常
#define INTMODULE_DUMMY_ERR_JSON_OBJ_EMPTY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, INT_MOD_DUMMY_ERR_JSON_OBJ_EMPTY)//json对象为空
#define INTMODULE_DUMMY_ERR_SET_EMPTY			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, INT_MOD_DUMMY_ERR_SET_EMPTY)//模块集合为空
#define INTMODULE_DUMMY_ERR_MATCH			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, INT_MOD_DUMMY_ERR_MATCH)//模块匹配失败
#define INTMODULE_DUMMY_ERR_INITED			GAVIN_DEF_ERR(GAVIN_MODE_ID_INT_MOD_DUMMY, GAVIN_ERR_LEVEL_ERROR, INT_MOD_DUMMY_ERR_INITED)//module已经初始化

#endif 
